### ISSUE TITLE
Cannot build this repo

### ISSUE THREAD

**Issue by syky27** [llvm-class/project#4]
Hi, irresponsibly I got to solving this task today. I am having trouble with building this repo.

No matter what I try I always get error like this:

```
╭─syky at aluminium in ~/bi-llvm/project/build on master✘✘✘ using ‹2.2.3›
╰─± cmake --build .
Scanning dependencies of target rift
[  7%] Building CXX object CMakeFiles/rift.dir/ast.cpp.o
[ 15%] Building CXX object CMakeFiles/rift.dir/boxing_removal.cpp.o
[ 23%] Building CXX object CMakeFiles/rift.dir/compiler.cpp.o
In file included from /Users/syky/bi-llvm/project/compiler.cpp:8:
/Users/syky/bi-llvm/project/type_checker.h:84:10: warning: 'runOnFunction' overrides a member function but is not
      marked 'override' [-Winconsistent-missing-override]
    bool runOnFunction(llvm::Function & f);
         ^
/usr/local/include/llvm/Pass.h:305:16: note: overridden virtual function is here
  virtual bool runOnFunction(Function &F) = 0;
               ^
1 warning generated.
[ 30%] Building CXX object CMakeFiles/rift.dir/gc.cpp.o
[ 38%] Building CXX object CMakeFiles/rift.dir/lexer.cpp.o
[ 46%] Building CXX object CMakeFiles/rift.dir/main.cpp.o
/Users/syky/bi-llvm/project/main.cpp:22:25: error: attempt to use a deleted function
    Environment * env = new Environment(nullptr);
                        ^
/Users/syky/bi-llvm/project/gc.h:462:10: note: 'operator delete' has been explicitly marked deleted here
    void operator delete(void*) = delete;
         ^
/Users/syky/bi-llvm/project/main.cpp:66:29: error: attempt to use a deleted function
        Environment * env = new Environment(nullptr);
                            ^
/Users/syky/bi-llvm/project/gc.h:462:10: note: 'operator delete' has been explicitly marked deleted here
    void operator delete(void*) = delete;
         ^
/Users/syky/bi-llvm/project/main.cpp:81:5: error: attempt to use a deleted function
    new Environment(nullptr);
    ^
/Users/syky/bi-llvm/project/gc.h:462:10: note: 'operator delete' has been explicitly marked deleted here
    void operator delete(void*) = delete;
         ^
/Users/syky/bi-llvm/project/gc.h:88:49: warning: field 'node' is uninitialized when used here [-Wuninitialized]
    Page() : first(reinterpret_cast<uintptr_t>(&node[0])),
                                                ^
/Users/syky/bi-llvm/project/gc.h:188:22: note: in instantiation of member function 'gc::Page<Environment>::Page'
      requested here
        auto p = new Page<T>;
                     ^
/Users/syky/bi-llvm/project/gc.h:313:31: note: in instantiation of member function 'gc::Arena<Environment>::alloc'
      requested here
        auto res = arena<T>().alloc(false);
                              ^
/Users/syky/bi-llvm/project/gc.h:285:23: note: in instantiation of function template specialization
      'gc::GarbageCollector::doAlloc<Environment>' requested here
        return inst().doAlloc<T>();
                      ^
/Users/syky/bi-llvm/project/gc.h:459:38: note: in instantiation of function template specialization
      'gc::GarbageCollector::alloc<Environment>' requested here
        return gc::GarbageCollector::alloc<OBJECT>();
                                     ^
/Users/syky/bi-llvm/project/main.cpp:22:25: note: in instantiation of member function
      'HeapObject<Environment>::operator new' requested here
    Environment * env = new Environment(nullptr);
                        ^
In file included from /Users/syky/bi-llvm/project/main.cpp:8:
In file included from /Users/syky/bi-llvm/project/runtime.h:16:
/Users/syky/bi-llvm/project/gc.h:89:39: warning: field 'node' is uninitialized when used here [-Wuninitialized]
    last(reinterpret_cast<uintptr_t>(&node[pageSize - 1])) {
                                      ^
2 warnings and 3 errors generated.
make[2]: *** [CMakeFiles/rift.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/rift.dir/all] Error 2
make: *** [all] Error 2

```

Somehow I have no idea how to fix this... I have been trying to for past 6 hours with different results, but none of them actually lead to solution. Can you please help me?

**Comment by fghibellini** [comment]
on linux it builds without any problem with the sequence:

```
mkdir build
cd build
cmake ..
make
```

if you're building it on a mac it's likely some difference in the c++ compiler.

**Comment by syky27** [comment]
Well, what I also tried tho. On Xubuntu 14.04 and also Macox El Capitan... no success there :(

**Comment by fghibellini** [comment]
I would probably try to install a newer version of gcc on the Xubuntu machine since it comes with gcc-4.8.2 by default and I am compiling with 5.2.0

**Comment by syky27** [comment]
Will do, thanks.

**Comment by syky27** [comment]
Well, after clean reinstalation of virtual Ubuntu 14.04 I finally managed to build everything on one try. Thanks for help.
